### ISSUE TITLE
makeRestCall POST/PUT/DELETE missing content-type:application/json

### ISSUE THREAD

**Issue by shanecrockett** [Enzoic/enzoic-javascript-client#1]
The PasswordPing.prototype.makeRestCall() method does not allow for POST/PUT/DELETE methods since the API requires the request.headers['content-type'] to be set. Trying to POST data to the API using this method results in the following error:
`{
    "message": "Unexpected error from PasswordPing API",
    "error": "400 Bad Request"
}`

DELETE method requires request.headers['content-length'], otherwise 400 bad request.

Also, additional response codes would need to be handled for POST/PUT methods (201 specifically)

**Comment by Enzoic** [comment]
This is corrected in the latest push and in version 1.1.0 in npm.  This version also adds methods for the alert subscriptions APIs.
